// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gziitjafxcblntbbmrxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aWl0amFmeGNibG50YmJtcnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODg4MjYsImV4cCI6MjA1ODY2NDgyNn0.rcWsKEOKF8n0BQJiXBD3AbIAmU1l9ucm5SILLuZIi4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);